### ISSUE TITLE
How to register using Flexisip

### ISSUE THREAD

**Issue by isikozsoy** [BelledonneCommunications/flexisip#101]
Hi! I would like to register Flexisip by using Linphone. How can I use flexisip as central? I couldn’t find document on the internet. I have limited knowledge about the topic so please explain in detail. I would like to create two user on flexisip and call each other on Linphone.

**Comment by Emil-Suleymanli** [comment]
Hi,

This is an example for the minimal config: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Minimal%20registrar%20with%20authentication/

For the domain part, you can use xip.io. So, if your IP address is 192.168.1.1, it would be sip.192.168.1.1.xip.io
If you are working in VirtualBox, you can have 3 VMs (one for Flexisip server, the other 2 for two clients)  with NAT network. Otherwise, you can host it on the cloud.

**Comment by August1023** [comment]
I tried the minimum configuration, but I couldn't. Why did the authorities not make it clear?
