### ISSUE TITLE
NAT configuration for flexisip as SIP proxy and Asterisk as SIP backend server.

### ISSUE THREAD

**Issue by E2-Sterlin** [BelledonneCommunications/flexisip#173]
I have configured Flexisip as SIP Proxy server and Asterisk as SIP backend server.
Call is not working in public network, but its working in local network.
I have configured NAT in both the server(Flexisip and Asterisk).
Kindly suggest me where am I lagging ?

If possible kindly refer NAT related configuration for SIP server and flexisip.

Thanks in advance :)

**Comment by Failxxx** [comment]
Hello,

It is hard to answer without detailed information.
However, I would suggest you to try the new strategy in the `module::NatHelper` (since Flexisip 2.4.0): https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/A.%20Configuration%20Reference%20Guide/2.4.0/module/NatHelper

Sincerely,
Félix.
