### ISSUE TITLE
setup a Flexisip proxy server acting as a front-end for backend SIP server.

### ISSUE THREAD

**Issue by syco** [BelledonneCommunications/flexisip#41]
I tried this config for a few days and I read the documentation multiple times, but it didn't help.
I'm using this docker container to start an asterisk instance with flexisip in front.
sycolth.mooo.com points to 172.17.0.2, the default ip for the first docker container.
I then open 2 linphone and register them one to sycolth.mooo.com:5060 (asterisk) and the other through sycolth.mooo.com:6060 (flexisip).
At this point I have 1000 directly to asterisk, 1001 through flexisip.
1000 can call 1001, and 1001 can answer or reject the call.
If it answer, then hangup doesn't work, doesn't matter what party hangups first.
1001 can't call 1000.
Is there anyone with a good heart can help me understand this config or the documentation?
Thanks

[asterisk-flexisip.tar.gz](https://github.com/BelledonneCommunications/flexisip/files/2164377/asterisk-flexisip.tar.gz)

**Comment by vobi2017** [comment]
Hey I'm trying to do the same did you happen to get this working mate?

**Comment by syco** [comment]
Hi,
I got it to work on a separate server. Not on the same server and different ports as I wanted.
But I only kept it running for a few weeks, then realized I don't like linphone android and dropped it..
Anyway, this is the configuration I used (or at lease the configuration in my gitlab, unfortunately I only have 1 commit, so I can't retrieve any more history):
[flexisip.txt](https://github.com/BelledonneCommunications/flexisip/files/3145388/flexisip.txt)

sip.rinaudo.net and flexisip.rinaudo.net are pointed to 2 separate servers, both in dmz.

**Comment by vobi2017** [comment]
OK cool, thanks mate you’re a champion.



*From:* Alberto Rinaudo <notifications@github.com>
*Sent:* Sunday, 5 May 2019 6:09 PM
*To:* BelledonneCommunications/flexisip <flexisip@noreply.github.com>
*Cc:* vobi2017 <mr@vobi.com.au>; Comment <comment@noreply.github.com>
*Subject:* Re: [BelledonneCommunications/flexisip] setup a Flexisip proxy
server acting as a front-end for backend SIP server. (#41)



Hi,
I got it to work on a separate server. Not on the same server and different
ports as I wanted.
But I only kept it running for a few weeks, then realized I don't like
linphone android and dropped it..
Anyway, this is the configuration I used (or at lease the configuration in
my gitlab, unfortunately I only have 1 commit, so I can't retrieve any more
history):
flexisip.txt
<https://github.com/BelledonneCommunications/flexisip/files/3145388/flexisip.txt>

sip.rinaudo.net and flexisip.rinaudo.net are pointed to 2 separate servers,
both in dmz.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BelledonneCommunications/flexisip/issues/41#issuecomment-489411450>,
or mute the thread

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
